image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd /workspace/go-echo-demo/server &&  go get -u && mysql < /workspace/go-echo-demo/server/docker/mysql/data.sql
    command: cd /workspace/go-echo-demo/server &&  go run ./main.go
ports:
  - port: 8080
    onOpen: open-preview
