version: "3"
services:
  dev:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 1234:8970
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - ./:/root/app
      - ./docker/wait-for-it.sh:/root/wait-for-it.sh
    command: /bin/bash -c  "chmod +x /root/wait-for-it.sh;/root/wait-for-it.sh mysql:3306 -- echo mysql launch success;cd /root/app/;air" #./run.sh ./debug_bin;
  mysql:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1233:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=sukeaiya
      - LANG=C.UTF-8
      - default_authentication_plugin=mysql_native_password
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci

    # - ./config/docker/mysql/conf/my.conf:/etc/mysql/my.cnf
