version: '3'
services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 1234:8080
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - ~/.ssh:/root/.ssh
      - ../../:/root/app
      # - /Volumes/File/SDK/gowork:/root/go
      - ~/.docker-cache/go:/usr/local/go
      - ~/.docker-cache/docker-go-path:/root/go
      - ./wait-for-it.sh:/root/wait-for-it.sh
    # command: /bin/sh -c "while true;do echo hello world!;sleep 1;done;"
    command: /bin/bash -c  "chmod +x /root/wait-for-it.sh;/root/wait-for-it.sh mysql:3306 -- echo mysql launch success;cd /root/app/server;chmod +x ./run.sh;while true;do echo hello world!;sleep 1;done;" #./run.sh ./debug_bin;
  mysql:
    image: mysql
    ports:
      - 1233:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - mysql_root_password=123456
      - LANG=C.UTF-8
      - default_authentication_plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      # - ./config/docker/mysql/conf/my.conf:/etc/mysql/my.cnf
